export const GAME_CONFIG = {
  VIRTUAL_WIDTH: 800,
  VIRTUAL_HEIGHT: 450,

  STATE: {
    MENU: 'MENU',
    PLAYING: 'PLAYING',
    GAMEOVER: 'GAMEOVER',
    SHOP: 'SHOP',
    CHALLENGES: 'CHALLENGES',
    OPTIONS: 'OPTIONS',
    GAMEOVER_SCREEN: 'GAMEOVER_SCREEN',
  },

  // === Physics ===
  GRAVITY: 1.0,
  FALL_GRAVITY_MULTIPLIER: 1.45,
  MAX_FALL_SPEED: 17,
  BASE_SPEED: 6.0,
  MAX_SPEED: 14.0,
  SPEED_ACCELERATION: 0.0006,
  COIN_SPEED_BONUS: 0.05,

  // === Player ===
  PLAYER_START_X: 280,
  PLAYER_START_Y: 120,
  PLAYER_WIDTH: 50,
  PLAYER_HEIGHT: 66,
  MAX_HEALTH: 3,
  INVINCIBILITY_FRAMES: 60,

  // === Jump ===
  JUMP_FORCE: -15.5,
  POWER_JUMP_FORCE: -25.0,
  MAX_MIDAIR_JUMPS: 1,
  DOUBLE_TAP_WINDOW: 300,
  POWER_JUMP_COOLDOWN: 400,

  // === Platforms ===
  GROUND_Y: 200,
  PLATFORM_HEIGHT: 220,           // ← doubled (was 110)
  MIN_PLATFORM_WIDTH: 180,
  MAX_PLATFORM_WIDTH: 420,
  STANDARD_GAP: 110,              // ← restored
  MAX_GAP: 220,                   // ← restored

  SPRITE_OFFSET_Y: 12,
  // === Items (bigger sizes) ===
  ITEM_TYPES: {
    COIN: 'COIN',
    SPIKE: 'SPIKE',
    BOOST_PAD: 'BOOST_PAD',
    POWER_ORB: 'POWER_ORB',
  },

  COIN_SIZE: 36,
  SPIKE_WIDTH: 42,
  SPIKE_HEIGHT: 34,
  BOOST_PAD_WIDTH: 56,
  BOOST_PAD_HEIGHT: 20,
  POWER_ORB_SIZE: 40,
  BOOST_SPEED_MULTIPLIER: 1.4,

  POWER_TYPES: {
    SPEED: 'SPEED',
    FLOAT: 'FLOAT',
    MAGNET: 'MAGNET',
    SHIELD: 'SHIELD',
    GRAVITY_FLIP: 'GRAVITY_FLIP',
    SCORE_DOUBLER: 'SCORE_DOUBLER',
  },

  POWER_DURATION: {
    SPEED: 300,
    FLOAT: 300,
    MAGNET: 360,
    SHIELD: 0,
    GRAVITY_FLIP: 180,
    SCORE_DOUBLER: 300,
  },

  SPEED_POWER_BOOST: 3.5,
  FLOAT_GRAVITY_MULT: 0.45,
  FLOAT_JUMP_MULT: 0.75,
  MAGNET_RADIUS: 180,

  COMBO_TIMEOUT_FRAMES: 300,
  COMBO_SCORE_BONUS: 0.2,

  // === Water (raised so it's more prominent) ===
  WATER_LEVEL_Y: 340,
  FALL_DEATH_Y: 470,

  MUSIC_BASE_VOLUME: 0.5,
  MUSIC_FADE_IN_MS: 800,
  MUSIC_FADE_OUT_MS: 600,
  MUSIC_MAX_RATE: 1.15,
};