// Offline TTS quip library, organized by trigger category
// Developer easter eggs: "Vhite" and "Victor" sprinkled throughout

export const QUIPS = {
  DEATH: [
    "Splash. That's gonna leave a mark.",
    "The water wins this round.",
    "You sank faster than a brick.",
    "Error four-oh-four: Victor not found.",
    "Down you go, champion.",
    "That was wet. Very wet.",
    "The floor was lava. The water was worse.",
    "Better luck next reboot.",
    "Well, that escalated quickly.",
    "Back to the drawing board.",
    "You fell like a rock.",
    "Gravity: 1, You: 0.",
    "The water called. It said hi.",
    "That's going to sting tomorrow.",
    "Blooper reel material right there.",
    "Clean-up on aisle runner.",
    "You got dunked.",
    "Splish splash, you took a bath.",
    "Somebody call a lifeguard.",
    "Not the ending you hoped for.",
    "Vhite would say: maybe try jumping next time.",
    "Victor's code did not save you here.",
    "This is not the run Vhite would have shipped.",
    "Down the drain, courtesy of physics.",
    "The cyber-water claims another victim.",
    "Shields down. Dignity gone.",
    "That was less 'dash' and more 'splash'.",
    "You made a splash. Literally.",
    "Another one bites the fluid.",
    "Submerged and defeated.",
  ],
  LONG_AIR: [
    "Nice hang time!",
    "Are you a bird?",
    "Gravity called, it wants you back.",
    "Frequent flyer miles incoming.",
    "That was a moon jump.",
    "The sky isn't the limit.",
    "Air time champion!",
    "Should we call NASA?",
    "You're practically flying.",
    "Icarus would be proud.",
    "How's the view up there?",
    "Long jump legend.",
    "Victor built you wings, not that.",
    "Floating like Vhite's reputation.",
    "You've been in the air longer than this build.",
    "Houston, we have a jumper.",
    "Is that a bird? A plane? No, it's you.",
    "Sky high and stylish.",
  ],
  HIGH_SPEED: [
    "Blazing fast!",
    "You're on fire!",
    "Breaking the sound barrier!",
    "Speed demon!",
    "Feet don't fail me now!",
    "Faster than light!",
    "Zoom zoom zoom!",
    "Sonic would be jealous.",
    "Mach one achieved!",
    "Speedrun mode: engaged.",
    "You're tearing up the track!",
    "Turbo activated!",
    "Vhite designed this for speed.",
    "Victor's engine is roaring!",
    "Faster than Vhite shipping an update.",
    "You're outrunning the code itself!",
    "Velocity: Off the charts.",
    "Hypersonic!",
  ],
  HIGH_SCORE: [
    "New high score! Legendary!",
    "You just rewrote the record books!",
    "Unstoppable!",
    "That's a new personal best!",
    "The leaderboard bows to you.",
    "Champion status achieved!",
    "Record smashed!",
    "A new king of the run!",
    "Banner moment!",
    "That's how legends play!",
    "Victor would put this on his wall.",
    "Vhite's coding paid off!",
    "The devs are celebrating!",
    "Screen this. Frame it. Send it to Vhite.",
    "You've made the developer proud.",
    "Peak performance achieved!",
  ],
  COMBO_5: [
    "Combo! Nice.",
    "Five in a row!",
    "You're heating up!",
    "Combo streak started!",
    "Chain reaction!",
    "Five-piece combo!",
  ],
  COMBO_10: [
    "Ten combo! Unreal!",
    "You're a machine!",
    "Combo master!",
    "Double digits!",
    "Combo madness!",
    "Vhite's combo algorithm is working!",
    "Victor coded this for exactly this moment.",
  ],
  COMBO_15: [
    "Fifteen combo! Godlike!",
    "Absolutely unstoppable!",
    "Are you even human?",
    "Combo god tier!",
    "This is art!",
    "Vhite is watching in disbelief.",
    "Combo streak worthy of a Victor badge.",
  ],
  COMBO_20: [
    "Twenty combo! What?!",
    "Combo royalty!",
    "You broke the combo meter!",
    "Impossible!",
    "Legendary streak!",
    "This combo is named after Victor now.",
    "Vhite just fainted.",
    "Combo perfection achieved!",
  ],
  SHIELD_SAVE: [
    "Shield saved you!",
    "That was close!",
    "Shield absorbed the hit!",
    "Bubble saved your bacon!",
    "Shield says no.",
    "Protected like Vhite's build pipeline.",
    "Shield tech by Victor Industries.",
    "You live to run another second!",
  ],
  HEART_LOST: [
    "Ouch! That hurt.",
    "You lost a heart.",
    "Watch the spikes!",
    "Bleeding but alive!",
    "That left a scar!",
    "Vhite feels your pain.",
    "Victor coded the spikes. Sorry.",
    "One heart down. Two to go.",
    "Ouch. That's going to slow you down.",
  ],
  POWER_UP: [
    "Power up!",
    "Boost activated!",
    "Cyber upgrade online!",
    "Systems enhanced!",
    "Feeling stronger!",
    "Buff engaged!",
    "Vhite's power grid has blessed you!",
    "Victor's upgrade installed successfully.",
    "Enhanced mode: ON.",
    "This is what Vhite intended.",
  ],
  START: [
    "Go!",
    "Run!",
    "Showtime!",
    "Let's go!",
    "Here we go!",
    "Light it up!",
    "Vhite says: run!",
    "Victor's code initialized. GO!",
    "Into the neon!",
    "Dash time!",
  ],
};

export function getRandomQuip(category) {
  const list = QUIPS[category];
  if (!list || list.length === 0) return '';
  return list[Math.floor(Math.random() * list.length)];
}